steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'storage'
      - 'cp'
      - './code_base' 
      - 'gs://bct-base-adventureworks/scripts/'
      - '--recursive'

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET